using Login.Infrastructure.Model;
using Login.Infrastructure.Model.Catalog;
using Microsoft.EntityFrameworkCore;

namespace Login.WebApi.Seeding;

public static class CatalogSeeder
{
    public static async Task SeedAsync(DataContext db)
    {
        if (await db.CatalogProcessTypes.AnyAsync()) return;

        db.CatalogProcessTypes.AddRange(Build());
        await db.SaveChangesAsync();
    }

    static CatalogStage S(string name, params string[] subs) => new()
    {
        Name = name,
        SubStages = subs.Where(s => !string.IsNullOrWhiteSpace(s))
                        .Select(s => new CatalogSubStage { Name = s.Trim() })
                        .ToList()
    };

    static IEnumerable<CatalogProcessType> Build() =>
    [
        new()
        {
            Name = "INSOLVENCIA",
            Stages =
            [
                S("PREPARATORIO PROCESO",
                    "ABOGADO RECIBE CORREO ELECTRÓNICO CON ASIGNACIÓN",
                    "INSTRUCCIÓN DE NO REPRESENTAR AL BANCO O RENUNCIAR A LA ACREENCIA"),
                S("ADMISIÓN",
                    "FECHA DE ADMISIÓN",
                    "AL COBRO JURIDICO",
                    "PAGO DIRECTO",
                    "FAG/FNG",
                    "LEASING"),
                S("ENVÍO COMUNICADO LEASING",
                    "ABOGADO ENVÍA COMUNICADO AL CLIENTE",
                    "EL CLIENTE RESPONDE COMUNICADO"),
                S("ESTADO LEASING AL ENVIAR COMUNICADO",
                    "AL DIA",
                    "VENCIDO SIN RESTITUCIÓN",
                    "VENCIDO CON RESTITUCIÓN (sin sentencia)",
                    "NO APLICA CON SENTENCIA"),
                S("OBJECIONES Y/O CONTROVERSIAS",
                    "EL BANCO PRESENTA CONTROVERSIA",
                    "UN TERCERO OBJETA",
                    "UN TERCERO PRESENTA CONTROVERSIAS",
                    "RESUELVE CONTROVERSIA",
                    "SUSTENTACIÓN OBJECIÓN O CONTROVERSIA",
                    "DESCORRE TRASLADO OTRAS PARTES",
                    "ENVÍA AL JUZGADO CIVIL MUNICIPAL",
                    "EL JUZGADO RESUELVE OBJECIÓN",
                    "CONVOCA NUEVA FECHA DE AUDIENCIA",
                    "AUTO DECRETA PRUEBAS",
                    "AUDIENCIA DE PRUEBAS"),
                S("NEGOCIACIÓN DE DEUDAS",
                    "AUDIENCIA 1", "AUDIENCIA 2", "AUDIENCIA 3",
                    "AUDIENCIA 4", "AUDIENCIA 5", "AUDIENCIA 6",
                    "AUDIENCIA 7", "AUDIENCIA 8", "AUDIENCIA 9"),
                S("PROPUESTA DE PAGO NEGOCIACION DE DEUDAS",
                    "PRESENTACIÓN PROPUESTA DE PAGO",
                    "DECISIÓN COMITÉ POSITIVO",
                    "DECISIÓN COMITÉ NEGATIVO"),
                S("DENUNCIA INCUMPLIMIENTO SIN ACUERDO",
                    "DENUNCIA INCUMPLIMIENTO GASTOS DE ADMINISTRACIÓN"),
                S("TERMINACIÓN",
                    "TERMINACION POR DESISTIMIENTO DEL TRÁMITE_NEG. DEUDA",
                    "TERMINACION POR RECHAZO DEL TRAMITE_ NEG. DEUDA",
                    "TERMINACION POR PAGO TOTAL_ NEG. DEUDA",
                    "TERMINACION POR PAGO DEL ACUERDO DE NEGOCIACIÓN_ NEG. DEUDA",
                    "TERMINACION POR VENTA DE CARTERA INDIVIDUAL_NEG. DEUDA",
                    "TERMINACION POR DESISTIMIENTO TÁCITO _LIQ. PATR",
                    "TERMINACION POR ADJUDICACION PARCIAL O TOTAL_LIQ. PATR",
                    "TERMINACION POR VENTA DE CARTERA INDIVIDUAL_LIQ. PATR",
                    "TERMINACION POR MUERTE DEL DEUDOR_LIQ. PATR",
                    "RECHAZO POR FALTA DE REQUISITOS_LIQ. PATR"),
                S("RESULTADO NEGOCIACIÓN DE DEUDAS",
                    "UN TERCERO IMPUGNA EL ACUERDO",
                    "TRASLADO IMPUGNACIÓN",
                    "RESUELVE IMPUGNACIÓN",
                    "ENVÍA AL JUZGADO CIVIL MUNICIPAL",
                    "EL JUZGADO RESUELVE IMPUGNACIÓN",
                    "CONVOCA NUEVA FECHA DE AUDIENCIA"),
                S("ACUERDO DE PAGO CELEBRADO"),
                S("FRACASO DE ACUERDO"),
                S("ACUERDO BILATERAL"),
                S("TRAMITE INCUMPLIMIENTO DEL ACUERDO",
                    "EN ESTUDIO LA DENUNCIA DEL INCUMPLIMIENTO",
                    "EL BANCO DENUNCIA INCUMPLIMIENTO",
                    "UN TERCERO DENUNCIA EL INCUMPLIMIENTO",
                    "EL DEUDOR DENUNCIA EL INCUMPLIMIENTO",
                    "SEÑALA FECHA PARA AUDIENCIA DE INCUMPLIMIENTO",
                    "AUDIENCIA DE INCUMPLIMIENTO"),
                S("REFORMA DEL ACUERDO",
                    "EL DEUDOR SOLICITA REFORMA AL ACUERDO",
                    "ACREEDORES SOLICITAN REFORMA AL ACUERDO",
                    "SEÑALA FECHA PARA AUDIENCIA DE REFORMA AL ACUERDO",
                    "AUDIENCIA DE REFORMA AL ACUERDO",
                    "IMPUGNA REFORMA",
                    "RESUELVE IMPUGNACION"),
                S("RESUELVE APERTURA LIQUIDACIÓN PATRIMONIAL",
                    "ADMITE APERTURA LIQUIDACIÓN PATRIMONIAL",
                    "INADMITE APERTURA LIQUIDACIÓN PATRIMONIAL",
                    "RECHAZA APERTURA LIQUIDACIÓN PATRIMONIAL"),
                S("LIQUIDACIÓN PATRIMONIAL",
                    "PENDIENTE APERTURA LIQUIDACIÓN PATRIMONIAL",
                    "SOLICITUD RELEVO DEL LIQUIDADOR",
                    "RELEVA LIQUIDADOR",
                    "TRASLADO DEL INVENTARIO",
                    "PRESENTACIÓN DE OBJECIONES",
                    "RESUELVE OBJECIONES AL INVENTARIO",
                    "FIJA FECHA AUDIENCIA",
                    "SOLICITUD ADJUDICACIÓN ESPECIAL (AFECTACIÓN A VIVIENDA FAMILIAR)",
                    "PROYECTO DE ADJUDICACIÓN",
                    "RENUNCIA A BIENES ADJUDICADOS",
                    "ACEPTA BIENES ADJUDICADOS",
                    "AUDIENCIA DE ADJUDICACIÓN",
                    "ACUERDO RESOLUTORIO",
                    "CONTABILIZACIÓN DE BIENES ADJUDICADOS",
                    "LIQUIDACIÓN EN CERO",
                    "RENDICION FINAL DE CUENTAS",
                    "LIQUIDADOR SE POSESIONA",
                    "REQUERIMIENTO AL LIQUIDADOR",
                    "LIQUIDADOR APORTA INVENTARIO",
                    "SOLICITUD TRASLADO AL INVENTARIO",
                    "SOLICITUD APROBAR INVENTARIO",
                    "SOLICITUD PROYECTO DE ADJUDICACIÓN",
                    "ACUERDO BILATERAL"),
                S("LIQUIDACIÓN PATRIMONIAL DIRECTA",
                    "ADMITE APERTURA",
                    "PRESENTACIÓN DE CRÉDITOS",
                    "TRASLADO A LA RELACIÓN DE ACREENCIAS",
                    "EL BANCO OBJETA",
                    "UN TERCERO OBJETA",
                    "RESUELVE OBJECIÓN DE CRÉDITOS",
                    "DECRETA PRUEBAS EN OBJECIÓN",
                    "AUDIENCIA DE PRUEBAS EN OBJECIÓN",
                    "LIQUIDADOR SE POSESIONA",
                    "REQUERIMIENTO AL LIQUIDADOR",
                    "SOLICITUD RELEVO",
                    "RELEVO LIQUIDADOR",
                    "LIQUIDADOR APORTA INVENTARIO",
                    "SOLICITUD TRASLADO AL INVENTARIO",
                    "TRASLADO AL INVENTARIO",
                    "SOLICITUD APROBAR INVENTARIO",
                    "PRESENTACIÓN DE OBJECIONES (AL INVENTARIO)",
                    "RESUELVE OBJECIONES AL INVENTARIO",
                    "FIJA FECHA AUDIENCIA",
                    "APLAZA AUDIENCIA DE ADJUDICACIÓN",
                    "SOLICITUD PROYECTO DE ADJUDICACIÓN",
                    "SOLICITUD ADJUDICACIÓN ESPECIAL",
                    "PROYECTO DE ADJUDICACIÓN",
                    "RENUNCIA A BIENES ADJUDICADOS",
                    "ACEPTA BIENES",
                    "AUDIENCIA DE ADJUDICACIÓN",
                    "CONTABILIZACIÓN DE BIENES ADJUDICADOS",
                    "LIQUIDACIÓN EN CERO",
                    "RENDICION DE CUENTAS FINALES",
                    "ACUERDO BILATERAL"),
                S("VENTA DE CARTERA INDIVIDUAL",
                    "OFERTA COMPRA DE CARTERA",
                    "DECISION COMITÉ"),
                S("REQUISITOS SARLAFT",
                    "PAGO DEL CLIENTE",
                    "NOTIFICACION DE LA CESION"),
                S("PQR'S",
                    "PRESENTACIÓN DERECHO DE PETICIÓN",
                    "RESPUESTA DERECHO DE PETICIÓN"),
                S("ACCION DE TUTELA",
                    "NOTIFICACIÓN ACCION DE TUTELA BBVA",
                    "RESPUESTA A TUTELA",
                    "FALLO TUTELA"),
            ]
        },
        new()
        {
            Name = "HIPOTECARIO",
            Stages =
            [
                S("DEMANDA",
                    "PRESENTACIÓN DEMANDA",
                    "INADMITE DEMANDA",
                    "SUBSANA DEMANDA",
                    "RECHAZA DEMANDA",
                    "SOLICITUD MANDAMIENTO DE PAGO",
                    "RECURSO REPOSICIÓN Y EN SUBSIDIO APELACIÓN AL AUTO QUE INADMITE LA DEMANDA",
                    "RECURSO REPOSICIÓN Y EN SUBSIDIO APELACIÓN AL AUTO QUE RECHAZA LA DEMANDA",
                    "RETIRO DE LA DEMANDA",
                    "INTERPONE ACCION DE TUTELA",
                    "RESUELVE ACCION DE TUTELA",
                    "RECHAZA DEMANDA POR COMPETENCIA"),
                S("MANDAMIENTO DE PAGO",
                    "LIBRA MANDAMIENTO DE PAGO",
                    "SOLICITUD ADICIÓN O CORRECCIÓN MANDAMIENTO DE PAGO",
                    "AUTO CORRIGE O ADICIONA MANDAMIENTO DE PAGO",
                    "RECURSO REPOSICIÓN Y EN SUBSIDIO APELACIÓN AL AUTO QUE NIEGA O LIBRA MANDAMIENTO DE PAGO PARCIAL",
                    "RESUELVE RECURSO DE REPOSICION",
                    "RESUELVE RECURSO DE APELACION",
                    "REQUIERE ART.317 DESISTIMIENTO TACITO",
                    "CUMPLE REQUERIMIENTO ART.317",
                    "INTERPONE RECURSO CONTRA REQUERIMIENTO ART. 317",
                    "RESUELVE RECURSO ART. 317"),
                S("NOTIFICACIÓN",
                    "ENVÍO CORREO ELECTRÓNICO NOTIFICACIÓN LEY 2213/2022",
                    "RESPUESTA DEL CORREO ELECTRÓNICO POSITIVA LEY 2213/2022",
                    "APORTA CONSTANCIA DE NOTIFICACIÓN LEY 2213/2022",
                    "RESPUESTA DEL CORREO NEGATIVA",
                    "ACEPTA NOTIFICACIÓN POR CORREO ELECTRÓNICO LEY 2213",
                    "ENVÍO CITACIÓN PARA NOTIFICACIÓN ART. 291",
                    "DEMANDADO SE NOTIFICA PERSONALMENTE",
                    "ENVIA NOTIFICACIÓN POR AVISO ART. 292",
                    "TIENE NOTIFICADO POR AVISO",
                    "SOLICITUD DE EMPLAZAMIENTO",
                    "ORDENA EMPLAZAMIENTO",
                    "NOMBRA CURADOR AD LITEM",
                    "EMPLAZAMIENTO HEREDEROS INDETERMINADOS",
                    "EMPLAZAMIENTO HEREDEROS DETERMINADOS",
                    "NOTIFICACIÓN POR CURADOR",
                    "NOTIFICACIÓN POR CONDUCTA CONCLUYENTE",
                    "NOTIFICACIÓN EXITOSA A TODOS LOS DEMANDADOS",
                    "NOTIFICACION POR WHATSAPP LEY 2213/2022",
                    "ENVIO CARTA NOTIFICACIÓN",
                    "CITACIÓN ART.291 POSITIVA",
                    "CITACIÓN ART.291 NEGATIVA",
                    "NOTIFICACIÓN POR ESTADO ART. 463",
                    "REQUIERE ART.317 DESISTIMIENTO TACITO",
                    "CUMPLE REQUERIMIENTO ART.317",
                    "INTERPONE RECURSO CONTRA REQUERIMIENTO ART. 317",
                    "RESUELVE RECURSO ART. 317"),
                S("EMBARGO",
                    "SOLICITUD MEDIDA CAUTELAR",
                    "DECRETA MEDIDA CAUTELAR",
                    "EXPEDICIÓN OFICIO DE EMBARGO",
                    "REGISTRO EMBARGO",
                    "RESPUESTA EMBARGO NEGATIVA",
                    "RESPUESTA EMBARGO POSITIVA",
                    "SOLICITUD CORRECCIÓN OFICIO DE EMBARGO",
                    "OFICIO CORREGIDO",
                    "MEDIDA CAUTELAR NO EFECTIVA POR EXTINCIÓN DE DOMINIO",
                    "SOLICITUD OFICIO DE EMBARGO",
                    "LLEGA OFICIO SOLICITANDO EMBARGO DE REMANENTES",
                    "SOLICITUD DE REMISION OFICIOS DE EMBARGO",
                    "INCIDENTE DE DESEMBARGO",
                    "DESCORRE TRASLADO DE DESEMBARGO",
                    "FIJA FECHA PARA AUDIENCIA DE INCIDENTE DE DESEMBARGO",
                    "MEDIDA CAUTELAR CON EMBARGO PREFERENTE",
                    "RESUELVE INCIDENTE DESEMBARGO EN PRIMERA INSTANCIA",
                    "INTERPONE RECURSO DE APELACION CONTRA DECISION QUE RESUELVE INCIDENTE",
                    "RESUELVE EN SEGUNDA INSTANCIA INCIDENTE DE DESEMBARGO"),
                S("EXCEPCIONES - AUDIENCIAS",
                    "PRESENTACIÓN EXCEPCIONES",
                    "TRASLADO EXCEPCIONES / CONTESTACIÓN EXCEPCIONES",
                    "FIJA FECHA AUDIENCIA 372 CGP",
                    "AUDIENCIA 372 CGP",
                    "FIJA FECHA AUDIENCIA 373 CGP",
                    "AUDIENCIA 373 CGP",
                    "SUSPENSION DE AUDIENCIA"),
                S("SECUESTRO",
                    "DECRETA SECUESTRO",
                    "SOLICITUD DESPACHO COMISORIO",
                    "EXPIDE DESPACHO COMISORIO",
                    "RADICACIÓN DESPACHO COMISORIO PARA SECUESTRO",
                    "FIJACIÓN FECHA DILIGENCIA DE SECUESTRO",
                    "DILIGENCIA DE SECUESTRO",
                    "OPOSICIÓN A LA DILIGENCIA DE SECUESTRO",
                    "RESUELVE OPOSICIÓN DILIGENCIA DE SECUESTRO",
                    "DILIGENCIA NO EFECTUADA",
                    "SOLICITA SECUESTRO",
                    "INCORPORA DESPACHO COMISORIO DILIGENCIA PRACTICADA",
                    "INCORPORA DESPACHO COMISORIO DILIGENCIA NO PRACTICADA",
                    "DEVUELVE DESPACHO COMISORIO SIN DILIGENCIAR"),
                S("SENTENCIA",
                    "SOLICITUD SENTENCIA",
                    "SENTENCIA FAVORABLE PRIMERA INSTANCIA",
                    "SENTENCIA DESFAVORABLE PRIMERA INSTANCIA",
                    "SOLICITUD DE ACLARACIÓN O CORRECCIÓN DE LA SENTENCIA",
                    "AUTO ACLARA O CORRIGE SENTENCIA",
                    "CONDENA EN COSTAS EN CONTRA DEL BANCO",
                    "SENTENCIA FAVORABLE SEGUNDA INSTANCIA",
                    "SENTENCIA DESFAVORABLE SEGUNDA INSTANCIA",
                    "ABOGADO EXTERNO DEVUELVE GARANTÍAS/PROCESO EN CURSO",
                    "DEVOLUCION GARANTIAS BANCO A CUSTODIO/PROCESO EN CURSO"),
                S("RECURSOS",
                    "PRESENTACIÓN RECURSO DE REPOSICIÓN",
                    "PRESENTACIÓN RECURSO DE APELACIÓN",
                    "ADMITE RECURSO APELACIÓN",
                    "SUSTENTACIÓN RECURSO APELACIÓN",
                    "SUSTENTACIÓN DEL NO RECURRENTE",
                    "DESISTIMIENTO DEL RECURSO DE REPOSICIÓN Y/O APELACIÓN",
                    "TRASLADO DEL RECURSO DE REPOSICIÓN Y/O APELACIÓN",
                    "RESUELVE RECURSO DE REPOSICIÓN Y/O APELACIÓN",
                    "INTERPONE RECURSO DE REPOSICION Y EN SUBSIDIO EXPEDICION DE COPIAS PARA QUEJA",
                    "RESUELVE REPOSICION Y ENVIA A REPARTO PARA QUEJA",
                    "CONCEDE QUEJA - ORDENA DAR TRAMITE A LA APELACION"),
                S("TERMINACIÓN",
                    "RADICA MEMORIAL BANCO SOLICITA TERMINAR PROC PAGO TOTAL",
                    "TERMINA PROCESO CUOTAS MORA",
                    "TERMINA PROCESO PAGO TOTAL",
                    "PAGO ARANCEL JUDICIAL",
                    "EN TRAMITE DESGLOSE",
                    "DEVOLUCION GARANTIAS AX AL BANCO",
                    "TERMINA PROCESO POR DESISTIMIENTO TÁCITO",
                    "RADICA MEMORIAL BANCO SOLICITA TERMINAR PROC PAGO CUOTA EN MORA",
                    "REGISTRO OFICIO DE DESEMBARGO",
                    "NOVACION Y/O TRANSACCION",
                    "DEVOLUCION GARANTÍAS BANCO A CUSTODIO",
                    "RADICA MEMORIAL BANCO SOLICITA TERMINAR PROC NOVACION Y/O TRANSACCION",
                    "TERMINACIÓN POR SENTENCIA DESFAVORABLE"),
                S("ENTREGA",
                    "ENTREGA FISICA INMUEBLE AL BANCO",
                    "SOLICITA DESPACHO COMISORIO",
                    "RADICA ANTE ENTIDAD COMPETENTE DESPACHO COMISORIO PARA ENTREGA",
                    "FIJA FECHA DILIGENCIA DE ENTREGA",
                    "DILIGENCIA DE ENTREGA EFECTIVA",
                    "DILIGENCIA DE ENTREGA NO EFECTIVA - CON OPOSICION",
                    "SOLICITUD DE TITULOS",
                    "SE ENTREGAN TÍTULOS JUDICIALES AL BANCO",
                    "REGISTRA ACTA DE REMATE"),
                S("NULIDAD",
                    "TRASLADO NULIDAD",
                    "RESUELVE NULIDAD PRIMERA INSTANCIA",
                    "RESUELVE NULIDAD SEGUNDA INSTANCIA",
                    "PRESENTA INCIDENTE NULIDAD - DEMANDADO / TERCERO",
                    "PRESENTA INCIDENTE NULIDAD - BANCO"),
                S("SUSPENSIÓN",
                    "SUSPENSION PROCESO POR INSOLVENCIA (IPNNC)",
                    "SUSPENSIÓN PROCESO POR ORDEN JUDICIAL",
                    "SUSPENSIÓN PROCESO POR ACUERDO DE PAGO",
                    "SUSPENSION PROCESO POR LEY 1116/06"),
                S("LIQUIDACIÓN",
                    "LIQUIDACION APROBADA SIN MEDIDA CAUTELAR",
                    "PRESENTACIÓN LIQUIDACIÓN DEL CRÉDITO",
                    "TRASLADO LIQUIDACIÓN DEL CRÉDITO",
                    "OBJETA LIQUIDACIÓN DEL CRÉDITO",
                    "APRUEBA LIQUIDACION DE CREDITO",
                    "MODIFICA LIQUIDACIÓN CRÉDITO",
                    "APRUEBA LIQUIDACION DE COSTAS",
                    "PRESENTACION ACTUALIZACION LIQUIDACION DEL CREDITO",
                    "APRUEBA ACTUALIZACION DE LA LIQUIDACION DEL CREDITO",
                    "ABOGADO EXTERNO DEVUELVE GARANTIAS/PROCESO EN CURSO",
                    "DEVOLUCION GARANTIAS BANCO A CUSTODIO/PROCESO EN CURSO"),
                S("AVALÚO",
                    "SOLICITUD DE AVALÚO COMERCIAL AL BANCO",
                    "SE APORTA AVALÚO CATASTRAL",
                    "SE APORTA AVALÚO COMERCIAL",
                    "TRASLADO AVALÚO",
                    "APROBACIÓN AVALÚO",
                    "NIEGA AVALUO"),
                S("REMATE",
                    "SOLICITUD FECHA DE REMATE",
                    "SOLICITUD ADJUDICACION POR CUENTA DEL CRÉDITO - FIJACIÓN FECHA DE REMATE",
                    "PRIMERA LICITACIÓN",
                    "SEGUNDA LICITACIÓN",
                    "TERCERA LICITACIÓN",
                    "CUARTA LICITACIÓN",
                    "REMATE DESIERTO",
                    "APRUEBA REMATE",
                    "APRUEBA ADJUDICACIÓN AL BANCO",
                    "DILIGENCIA EFECTIVA DE REMATE",
                    "ABOGADO EXTERNO ENVIA DOCUMENTOS AL BANCO PARA CONCEPTO GANF",
                    "ABOGADO EXTERNO RECIBE INSTRUCCIONES DE REMATE / CONCEPTO GANF",
                    "APRUEBA ADJUDICACIÓN AL TERCERO",
                    "PAGO IMPUESTO DE REMATE"),
                S("IMPULSO PROCESAL"),
            ]
        },
        new()
        {
            Name = "RESTITUCIÓN",
            Stages =
            [
                S("DEMANDA",
                    "PRESENTACIÓN DEMANDA",
                    "INADMITE DEMANDA",
                    "SUBSANA DEMANDA",
                    "RECHAZA DEMANDA",
                    "SOLICITUD ADMITIR DEMANDA",
                    "RECURSO REPOSICIÓN Y EN SUBSIDIO APELACIÓN AL AUTO QUE INADMITE LA DEMANDA",
                    "RECURSO REPOSICIÓN Y EN SUBSIDIO APELACIÓN AL AUTO QUE RECHAZA LA DEMANDA",
                    "RETIRO DE LA DEMANDA",
                    "INTERPONE ACCION DE TUTELA",
                    "RESUELVE ACCION DE TUTELA",
                    "RECHAZA DEMANDA POR COMPETENCIA"),
                S("ADMISIÓN DEMANDA",
                    "ADMITE DEMANDA",
                    "REQUIERE ART.317 DESISTIMIENTO TACITO",
                    "CUMPLE REQUERIMIENTO ART.317",
                    "INTERPONE RECURSO CONTRA REQUERIMIENTO ART. 317",
                    "RESUELVE RECURSO ART. 317",
                    "RESUELVE RECURSO DE APELACIÓN"),
                S("NOTIFICACIÓN",
                    "ENVÍO CORREO ELECTRÓNICO NOTIFICACIÓN LEY 2213/2022",
                    "RESPUESTA DEL CORREO ELECTRÓNICO POSITIVA LEY 2213/2022",
                    "APORTA CONSTANCIA DE NOTIFICACIÓN LEY 2213/2022",
                    "RESPUESTA DEL CORREO NEGATIVA",
                    "ACEPTA NOTIFICACIÓN POR CORREO ELECTRÓNICO LEY 2213",
                    "ENVÍO CITACIÓN PARA NOTIFICACIÓN ART. 291",
                    "DEMANDADO SE NOTIFICA PERSONALMENTE",
                    "ENVIA NOTIFICACIÓN POR AVISO ART. 292",
                    "TIENE NOTIFICADO POR AVISO",
                    "SOLICITUD DE EMPLAZAMIENTO",
                    "ORDENA EMPLAZAMIENTO",
                    "NOMBRA CURADOR AD LITEM",
                    "EMPLAZAMIENTO HEREDEROS INDETERMINADOS",
                    "NOTIFICACIÓN POR CURADOR",
                    "NOTIFICACIÓN POR CONDUCTA CONCLUYENTE",
                    "NOTIFICACIÓN EXITOSA A TODOS LOS DEMANDADOS",
                    "NOTIFICACION POR WHATSAPP LEY 2213/2022",
                    "ENVIO CARTA NOTIFICACIÓN",
                    "CURADOR NO ACEPTA NOMBRAMIENTO"),
                S("EXCEPCIONES - AUDIENCIAS",
                    "PRESENTACIÓN EXCEPCIONES",
                    "TRASLADO EXCEPCIONES",
                    "CONTESTACIÓN EXCEPCIONES",
                    "FIJA FECHA AUDIENCIA 372 CGP",
                    "AUDIENCIA 372 CGP",
                    "FIJA FECHA AUDIENCIA 373 CGP",
                    "AUDIENCIA 373 CGP",
                    "SUSPENSION DE AUDIENCIA"),
                S("SENTENCIA",
                    "SOLICITUD SENTENCIA",
                    "DICTA SENTENCIA PRIMERA INSTANCIA FAVORABLE",
                    "DICTA SENTENCIA PRIMERA INSTANCIA DESFAVORABLE",
                    "SOLICITUD DE ACLARACIÓN O CORRECCIÓN DE LA SENTENCIA",
                    "AUTO ACLARA O CORRIGE SENTENCIA",
                    "SENTENCIA SIN RESTITUCION BIEN MUEBLE",
                    "SENTENCIA FAVORABLE SEGUNDA INSTANCIA",
                    "SENTENCIA DESFAVORABLE SEGUNDA INSTANCIA",
                    "AX DEVUELVE GARANTIAS AL BANCO / PROCESO ACTIVO"),
                S("RECURSOS",
                    "PRESENTACIÓN RECURSO DE REPOSICIÓN",
                    "PRESENTACIÓN RECURSO DE APELACIÓN",
                    "ADMITE RECURSO APELACIÓN",
                    "SUSTENTACIÓN RECURSO APELACIÓN",
                    "SUSTENTACIÓN DEL NO RECURRENTE",
                    "SENTENCIA 2 INSTANCIA",
                    "DESISTIMIENTO DEL RECURSO DE REPOSICIÓN Y/O APELACIÓN",
                    "TRASLADO DEL RECURSO DE REPOSICIÓN Y/O APELACIÓN",
                    "RESUELVE RECURSO DE REPOSICIÓN",
                    "INTERPONE RECURSO DE REPOSICION Y EN SUBSIDIO EXPEDICION DE COPIAS PARA QUEJA",
                    "RESUELVE REPOSICION Y ENVIA A REPARTO PARA QUEJA",
                    "CONCEDE QUEJA - ORDENA DAR TRAMITE A LA APELACION",
                    "RESUELVE RECURSO DE APELACION"),
                S("ENTREGA",
                    "SOLICITUD DESPACHO COMISORIO",
                    "RADICACIÓN DESPACHO COMISORIO PARA ENTREGA",
                    "FIJACIÓN FECHA DILIG DE ENTREGA",
                    "DILIGENCIA DE ENTREGA EFECTIVA",
                    "SUSPENSION DILIGENCIA POR PRIMERA VEZ",
                    "SUSPENSION DILIGENCIA POR SEGUNDA VEZ",
                    "SUSPENSION DILIGENCIA POR TERCERA VEZ",
                    "SUSPENSION DILIGENCIA POR CUARTA VEZ",
                    "ALLEGA DILIGENCIA DE ENTREGA",
                    "SOLICITUD DE AVALUO COMERCIAL",
                    "ENTREGA VOLUNTARIA POR PARTE DEL DEMANDADO",
                    "DILIGENCIA DE ENTREGA NO EFECTIVA - CON OPOSICION",
                    "ENTREGA FISICA INMUEBLE AL ABOGADO EXTERNO"),
                S("TERMINACIÓN",
                    "RADICA MEMORIAL BANCO SOLICITA TERMINAR PROC PAGO CUOTA EN MORA",
                    "BANCO SOLICITA TERMINAR PROC PAGO TOTAL - TRANSACCION",
                    "TERMINA PROCESO POR PAGO CANONES VENCIDOS",
                    "TERMINA PROCESO PAGO TOTAL - TRANSACCION",
                    "DEVOLUCION GARANTIAS AX AL BANCO",
                    "TERMINA PROCESO POR DESISTIMIENTO TÁCITO",
                    "SOLICITUD DESISTIR EFECTOS DE LA SENTENCIA DE RESTITUCIÓN",
                    "AUTO ACEPTA DESISTIMIENTO A EFECTOS DE LA SENTENCIA",
                    "AUTO NIEGA DESISTIMIENTO A EFECTOS DE LA SENTENCIA",
                    "TERMINACION POR REESTRUCTURACION",
                    "DEVOLUCION GARANTÍAS BANCO A CUSTODIO",
                    "TERMINACIÓN POR SENTENCIA DESFAVORABLE"),
                S("NULIDAD",
                    "TRASLADO NULIDAD",
                    "RESUELVE NULIDAD PRIMERA INSTANCIA",
                    "RESUELVE NULIDAD SEGUNDA INSTANCIA",
                    "PRESENTA INCIDENTE NULIDAD - BANCO",
                    "PRESENTA INCIDENTE DE NULIDAD DEMANDADO / TERCERO"),
                S("SUSPENSIÓN",
                    "SUSPENSION POR INSOLVENCIA P.N.N.C.",
                    "SUSPENSIÓN PROCESO POR ORDEN JUDICIAL",
                    "SUSPENSIÓN PROCESO POR ACUERDO DE PAGO",
                    "LEVANTA SUSPENSIÓN PROCESO",
                    "SUSPENSION POR LEY 1116/2006"),
                S("IMPULSO PROCESAL"),
            ]
        },
    ];
}
